/-
Copyright (c) 2026 Robert Joseph George and contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robert Joseph George
-/

module

public import Euler.Similarity.Coordinates
public import Euler.Equations.Stationary
public import Euler.Equations.Physical
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring

/-!
# Substituting the similarity profile

Here we compute the velocity formulas S270–S274 and substitute the profile
into the swirl and vorticity equations, S275–S290. The chain rule gives the
factors `(T-t)^(-2)` and `(T-t)^(-2-λ)` multiplying their residuals.

`Similarity/Traveling.lean` treats the elliptic equation and combines the three
equations. Setting `ε = 1` and `λ = 1/2` gives the calculation in Appendix C.
-/

@[expose] public section

open Euler.Calculus Euler.Coordinates

noncomputable section

namespace Euler

open Euler.Similarity

/-- Euler fields generated by a stationary profile triple. -/
def similarityFields
    (F : Profile) (lam singularTime : ℝ)
    (axialCenter : ℝ → ℝ) : Euler.Axisymmetric.ReducedFields where
  swirl := similarityScalar F.U 1 lam singularTime axialCenter
  vorticity := similarityScalar F.Ω (1 + lam) lam singularTime axialCenter
  streamFunction := similarityScalar F.Ψ (1 - lam) lam singularTime axialCenter

/-- Recovered radial velocity under the Euler similarity ansatz,
equations S270--S274. -/
theorem radialVelocity_similarityFields
    (F : Profile) (lam singularTime : ℝ)
    (axialCenter : ℝ → ℝ) (x : (ℝ^2)) {t : ℝ}
    (hPsi : DifferentiableAt ℝ F.Ψ
      (similarityCoordinates lam singularTime axialCenter x t))
    (ht : t < singularTime) :
    Euler.Axisymmetric.radialVelocity
        (similarityFields F lam singularTime axialCenter).streamFunction x t =
      backwardPowerScale (1 - lam) singularTime t *
        (-meridianR (similarityCoordinates lam singularTime axialCenter x t) *
          profileDZ F.Ψ
            (similarityCoordinates lam singularTime axialCenter x t)) := by
  unfold Euler.Axisymmetric.radialVelocity
  change
    -meridianR x *
        partialDeriv (1 : Fin 2)
          (fun y ↦
            similarityScalar F.Ψ (1 - lam) lam singularTime axialCenter y t) x = _
  rw [partialDeriv_similarityScalar F.Ψ (1 - lam) lam singularTime
    axialCenter (1 : Fin 2) x hPsi ht, similarityCoordinates_radial]
  rw [← backwardPowerScale_mul ht]
  simp only [profileDZ]
  ring

/-- Recovered axial velocity under the Euler similarity ansatz,
equations S270--S274. -/
theorem axialVelocity_similarityFields
    (F : Profile) (lam singularTime : ℝ)
    (axialCenter : ℝ → ℝ) (x : (ℝ^2)) {t : ℝ}
    (hPsi : DifferentiableAt ℝ F.Ψ
      (similarityCoordinates lam singularTime axialCenter x t))
    (ht : t < singularTime) :
    Euler.Axisymmetric.axialVelocity
        (similarityFields F lam singularTime axialCenter).streamFunction x t =
      backwardPowerScale (1 - lam) singularTime t *
        (2 * F.Ψ (similarityCoordinates lam singularTime axialCenter x t)
          + meridianR (similarityCoordinates lam singularTime axialCenter x t) *
              profileDR F.Ψ
                (similarityCoordinates lam singularTime axialCenter x t)) := by
  unfold Euler.Axisymmetric.axialVelocity
  change
    2 * similarityScalar F.Ψ (1 - lam) lam singularTime axialCenter x t
      + meridianR x *
        partialDeriv (0 : Fin 2)
          (fun y ↦
            similarityScalar F.Ψ (1 - lam) lam singularTime axialCenter y t) x = _
  rw [partialDeriv_similarityScalar F.Ψ (1 - lam) lam singularTime
    axialCenter (0 : Fin 2) x hPsi ht, similarityCoordinates_radial]
  rw [← backwardPowerScale_mul ht]
  simp only [similarityScalar, profileDR]
  ring

/-- The physical convection-varied swirl residual factors through the
stationary `U` residual, equations S255 and S275--S282. -/
theorem convectionVariedSwirlResidual_similarityFields
    (eps : ℝ) (F : Profile)
    (lam axialDrift singularTime : ℝ)
    (axialCenter : ℝ → ℝ) (x : (ℝ^2)) {t : ℝ}
    (hU : DifferentiableAt ℝ F.U
      (similarityCoordinates lam singularTime axialCenter x t))
    (hPsi : DifferentiableAt ℝ F.Ψ
      (similarityCoordinates lam singularTime axialCenter x t))
    (hcenter : HasDerivAt axialCenter
      (-axialDrift * backwardPowerScale (1 - lam) singularTime t) t)
    (ht : t < singularTime) :
    convectionVariedSwirlResidual eps
        (similarityFields F lam singularTime axialCenter).swirl
        (similarityFields F lam singularTime axialCenter).streamFunction x t =
      backwardPowerScale 2 singularTime t *
        swirlResidual eps lam axialDrift
          classicalAxisymmetricDifferential F.U F.Ψ
          (similarityCoordinates lam singularTime axialCenter x t) := by
  let y := similarityCoordinates lam singularTime axialCenter x t
  have htime :=
    (hasDerivAt_similarityScalar F.U 1 lam axialDrift singularTime
      axialCenter x hU hcenter ht).deriv
  have hUr := partialDeriv_similarityScalar F.U 1 lam singularTime
    axialCenter (0 : Fin 2) x hU ht
  have hUz := partialDeriv_similarityScalar F.U 1 lam singularTime
    axialCenter (1 : Fin 2) x hU ht
  have hPsiZ := partialDeriv_similarityScalar F.Ψ (1 - lam) lam
    singularTime axialCenter (1 : Fin 2) x hPsi ht
  have hvelocity :
      backwardPowerScale (1 - lam) singularTime t *
          backwardPowerScale (1 + lam) singularTime t =
        backwardPowerScale 2 singularTime t := by
    rw [backwardPowerScale_mul ht]
    congr 1
    ring
  have hstretch :
      backwardPowerScale 1 singularTime t *
          backwardPowerScale 1 singularTime t =
        backwardPowerScale 2 singularTime t := by
    rw [backwardPowerScale_mul ht]
    norm_num
  have htimeScale :
      backwardPowerScale (1 + 1) singularTime t =
        backwardPowerScale 2 singularTime t := by
    congr 1
    ring
  have hpsiScale :
      backwardPowerScale (1 - lam + lam) singularTime t =
        backwardPowerScale 1 singularTime t := by
    congr 1
    ring
  unfold convectionVariedSwirlResidual
  change
    deriv (fun s ↦
        similarityScalar F.U 1 lam singularTime axialCenter x s) t
      + eps * Euler.Axisymmetric.radialVelocity
          (similarityFields F lam singularTime axialCenter).streamFunction x t *
          partialDeriv (0 : Fin 2)
            (fun q ↦ similarityScalar F.U 1 lam singularTime axialCenter q t) x
      + eps * Euler.Axisymmetric.axialVelocity
          (similarityFields F lam singularTime axialCenter).streamFunction x t *
          partialDeriv (1 : Fin 2)
            (fun q ↦ similarityScalar F.U 1 lam singularTime axialCenter q t) x
      - 2 * similarityScalar F.U 1 lam singularTime axialCenter x t *
          partialDeriv (1 : Fin 2)
            (fun q ↦ similarityScalar F.Ψ (1 - lam) lam singularTime
              axialCenter q t) x = _
  rw [htime, hUr, hUz, hPsiZ,
    radialVelocity_similarityFields F lam singularTime
      axialCenter x hPsi ht,
    axialVelocity_similarityFields F lam singularTime
      axialCenter x hPsi ht]
  unfold swirlResidual radialTransportFactor axialTransport
  simp only [classicalAxisymmetricDifferential, similarityScalar,
    profileDR, profileDZ]
  rw [htimeScale, hpsiScale]
  linear_combination (norm := ring_nf)
    (eps * (-meridianR y * profileDZ F.Ψ y) * profileDR F.U y +
      eps * (2 * F.Ψ y + meridianR y * profileDR F.Ψ y) * profileDZ F.U y) * hvelocity -
      (2 * F.U y * profileDZ F.Ψ y) * hstretch
  simp only [y, profileDR, profileDZ]
  ring

/-- The physical convection-varied vorticity residual factors through the
stationary `Omega` residual, equations S256 and S283--S290. -/
theorem convectionVariedVorticityResidual_similarityFields
    (eps : ℝ) (F : Profile)
    (lam axialDrift singularTime : ℝ)
    (axialCenter : ℝ → ℝ) (x : (ℝ^2)) {t : ℝ}
    (hU : DifferentiableAt ℝ F.U
      (similarityCoordinates lam singularTime axialCenter x t))
    (hPsi : DifferentiableAt ℝ F.Ψ
      (similarityCoordinates lam singularTime axialCenter x t))
    (hOmega : DifferentiableAt ℝ F.Ω
      (similarityCoordinates lam singularTime axialCenter x t))
    (hcenter : HasDerivAt axialCenter
      (-axialDrift * backwardPowerScale (1 - lam) singularTime t) t)
    (ht : t < singularTime) :
    convectionVariedVorticityResidual eps
        (similarityFields F lam singularTime axialCenter).swirl
        (similarityFields F lam singularTime axialCenter).vorticity
        (similarityFields F lam singularTime axialCenter).streamFunction x t =
      backwardPowerScale (2 + lam) singularTime t *
        vorticityResidual eps lam axialDrift
          classicalAxisymmetricDifferential F.U F.Ψ F.Ω
          (similarityCoordinates lam singularTime axialCenter x t) := by
  let y := similarityCoordinates lam singularTime axialCenter x t
  have htime :=
    (hasDerivAt_similarityScalar F.Ω (1 + lam) lam axialDrift singularTime
      axialCenter x hOmega hcenter ht).deriv
  have hOmegaR := partialDeriv_similarityScalar F.Ω (1 + lam) lam
    singularTime axialCenter (0 : Fin 2) x hOmega ht
  have hOmegaZ := partialDeriv_similarityScalar F.Ω (1 + lam) lam
    singularTime axialCenter (1 : Fin 2) x hOmega ht
  have hUz := partialDeriv_similarityScalar F.U 1 lam singularTime
    axialCenter (1 : Fin 2) x hU ht
  have hvelocity :
      backwardPowerScale (1 - lam) singularTime t *
          backwardPowerScale (1 + 2 * lam) singularTime t =
        backwardPowerScale (2 + lam) singularTime t := by
    rw [backwardPowerScale_mul ht]
    congr 1
    ring
  have hstretch :
      backwardPowerScale 1 singularTime t *
          backwardPowerScale (1 + lam) singularTime t =
        backwardPowerScale (2 + lam) singularTime t := by
    rw [backwardPowerScale_mul ht]
    congr 1
    ring
  have htimeScale :
      backwardPowerScale (1 + lam + 1) singularTime t =
        backwardPowerScale (2 + lam) singularTime t := by
    congr 1
    ring
  have homegaScale :
      backwardPowerScale (1 + lam + lam) singularTime t =
        backwardPowerScale (1 + 2 * lam) singularTime t := by
    congr 1
    ring
  unfold convectionVariedVorticityResidual
  change
    deriv (fun s ↦
        similarityScalar F.Ω (1 + lam) lam singularTime axialCenter x s) t
      + eps * Euler.Axisymmetric.radialVelocity
          (similarityFields F lam singularTime axialCenter).streamFunction x t *
          partialDeriv (0 : Fin 2)
            (fun q ↦ similarityScalar F.Ω (1 + lam) lam singularTime
              axialCenter q t) x
      + eps * Euler.Axisymmetric.axialVelocity
          (similarityFields F lam singularTime axialCenter).streamFunction x t *
          partialDeriv (1 : Fin 2)
            (fun q ↦ similarityScalar F.Ω (1 + lam) lam singularTime
              axialCenter q t) x
      - 2 * similarityScalar F.U 1 lam singularTime axialCenter x t *
          partialDeriv (1 : Fin 2)
            (fun q ↦ similarityScalar F.U 1 lam singularTime axialCenter q t) x = _
  rw [htime, hOmegaR, hOmegaZ, hUz,
    radialVelocity_similarityFields F lam singularTime
      axialCenter x hPsi ht,
    axialVelocity_similarityFields F lam singularTime
      axialCenter x hPsi ht]
  unfold vorticityResidual radialTransportFactor axialTransport
  simp only [classicalAxisymmetricDifferential, similarityScalar,
    profileDR, profileDZ]
  rw [htimeScale, homegaScale]
  linear_combination (norm := ring_nf)
    (eps * (-meridianR y * profileDZ F.Ψ y) * profileDR F.Ω y +
      eps * (2 * F.Ψ y + meridianR y * profileDR F.Ψ y) * profileDZ F.Ω y) * hvelocity -
      (2 * F.U y * profileDZ F.U y) * hstretch
  simp only [y, profileDR, profileDZ]
  ring

end Euler
