module

public import Review.Definitions.Similarity.Basic
public import Review.Definitions.Equations.Stationary
public import Review.Definitions.Equations.Physical

/-! # Reconstructed similarity fields -/

@[expose] public noncomputable section

open Euler.Calculus Euler.Coordinates

namespace Euler

open Euler.Similarity

/-- Euler fields generated by a stationary profile triple. -/
def similarityFields
    (F : Profile) (lam singularTime : ℝ)
    (axialCenter : ℝ → ℝ) : Euler.Axisymmetric.ReducedFields where
  swirl := similarityScalar F.U 1 lam singularTime axialCenter
  vorticity := similarityScalar F.Ω (1 + lam) lam singularTime axialCenter
  streamFunction := similarityScalar F.Ψ (1 - lam) lam singularTime axialCenter

end Euler

end
